site_name: Blaze Black 2 Redux Wiki
site_url: https://smilingzero.github.io/BlazeBlack2Redux
site_description: A fanmade wiki for Blaze Black 2 Redux
site_author: Zero

repo_url: https://github.com/SmilingZero/BlazeBlack2Redux
